#!/bin/bash

echo "🚀 Backend Deployment Guide"
echo "=========================="
echo ""
echo "Choose your deployment platform:"
echo ""
echo "1️⃣  Railway (Recommended - Easy & Free tier)"
echo "2️⃣  Render (Alternative - Also has free tier)"
echo "3️⃣  Fly.io (Good for global deployment)"
echo "4️⃣  AWS EC2 (For production use)"
echo ""
read -p "Select option (1-4): " choice

case $choice in
  1)
    echo ""
    echo "📦 Deploying to Railway..."
    echo ""
    echo "Steps:"
    echo "1. Install Railway CLI:"
    echo "   npm install -g @railway/cli"
    echo ""
    echo "2. Login to Railway:"
    echo "   railway login"
    echo ""
    echo "3. Initialize project:"
    echo "   railway init"
    echo ""
    echo "4. Deploy:"
    echo "   railway up"
    echo ""
    echo "5. Get your URL:"
    echo "   railway open"
    echo ""
    echo "Railway will automatically detect the Dockerfile and deploy!"
    ;;
    
  2)
    echo ""
    echo "📦 Deploying to Render..."
    echo ""
    echo "Steps:"
    echo "1. Push code to GitHub (already done ✅)"
    echo ""
    echo "2. Go to https://render.com"
    echo ""
    echo "3. Connect your GitHub account"
    echo ""
    echo "4. Click 'New +' → 'Web Service'"
    echo ""
    echo "5. Select your repository: avifenesh/finding-apartment-tlv"
    echo ""
    echo "6. Use these settings:"
    echo "   - Name: yad2-apartment-finder"
    echo "   - Runtime: Docker"
    echo "   - Branch: main"
    echo ""
    echo "7. Click 'Create Web Service'"
    echo ""
    echo "Render will automatically deploy using the Dockerfile!"
    ;;
    
  3)
    echo ""
    echo "📦 Deploying to Fly.io..."
    echo ""
    echo "Steps:"
    echo "1. Install Fly CLI:"
    echo "   curl -L https://fly.io/install.sh | sh"
    echo ""
    echo "2. Login:"
    echo "   fly auth login"
    echo ""
    echo "3. Launch app:"
    echo "   fly launch --dockerfile Dockerfile"
    echo ""
    echo "4. Deploy:"
    echo "   fly deploy"
    echo ""
    echo "5. Open app:"
    echo "   fly open"
    ;;
    
  4)
    echo ""
    echo "📦 Deploying to AWS EC2..."
    echo ""
    echo "Steps:"
    echo "1. Launch EC2 instance (Ubuntu 22.04)"
    echo ""
    echo "2. SSH into instance and run:"
    echo "   git clone https://github.com/avifenesh/finding-apartment-tlv.git"
    echo "   cd finding-apartment-tlv"
    echo ""
    echo "3. Install Docker:"
    echo "   curl -fsSL https://get.docker.com -o get-docker.sh"
    echo "   sudo sh get-docker.sh"
    echo ""
    echo "4. Build and run:"
    echo "   sudo docker build -t yad2-finder ."
    echo "   sudo docker run -d -p 80:8000 --name yad2-app yad2-finder"
    echo ""
    echo "5. Configure security group to allow HTTP (port 80)"
    ;;
    
  *)
    echo "Invalid option!"
    exit 1
    ;;
esac

echo ""
echo "📝 After deployment:"
echo "1. Copy your backend URL"
echo "2. Update frontend/script.js with the new URL"
echo "3. Push to GitHub: git push origin gh-pages"
echo "4. Your app will be fully functional!"
echo ""
echo "Need help? Check BACKEND_DEPLOYMENT.md for detailed instructions."